version: '3.3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app_db
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis